trigger:
  branches:
    include:
    - master
  paths:
    include:
    - azure-pipelines.yml

stages:
- stage: build
  jobs:
  - job: build

    pool:
      vmImage: ubuntu-latest

    variables:
      sdkVersion: 3.1.x
      buildConfiguration: 'Release'

    steps:
    - task: UseDotNet@2
      displayName: dotnet sdk 2.x
      inputs:
        packageType: 'sdk'
        version: '2.x'

    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'project2-fakebook'
        organization: '2011-nov02-net'
        scannerMode: 'MSBuild'
        projectKey: '2011-nov02-net_project2-fakebook'
        extraProperties: 'sonar.exclusions=**/lib/**'

    - task: UseDotNet@2
      displayName: dotnet sdk $(sdkVersion)
      inputs:
        packageType: 'sdk'
        version: '$(sdkVersion)'


    - script: dotnet build --configuration $(buildConfiguration)
      displayName: dotnet build

    - task: SonarCloudAnalyze@1
      displayName: sonar run analysis

    - task: SonarCloudPublish@1
      displayName: sonar analysis publish
      inputs:
        pollingTimeoutSec: '300'

    - task: DotNetCoreCLI@2
      displayName: dotnet test
      inputs:
        command: 'test'
        arguments: '--configuration $(buildConfiguration)'
        publishTestResults: true

    - script: dotnet publish --configuration $(buildConfiguration) --output publish
      displayName: dotnet publish

    # - task: AzureRmWebAppDeployment@4
    #   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    #   inputs:
    #     ConnectionType: 'AzureRM'
    #     azureSubscription: 'Azure subscription 1(2c48e7d4-496d-4e6f-84af-fa49ea8ea9fe)'
    #     appType: 'webApp'
    #     WebAppName: ''
    #     packageForLinux: 'publish'
