#finished pipeline 
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - azure-pipelines.yml
    - 'backend/Fakebook'

stages:
- stage: build
  jobs:
  - job: build

    pool:
      vmImage: ubuntu-latest

    variables:
      sdkVersion: 3.1.x
      buildConfiguration: 'Release'

    steps:
    - task: UseDotNet@2
      displayName: dotnet sdk 2.x
      inputs:
        packageType: 'sdk'
        version: '2.x'

    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud'
        organization: '2011-nov02-net'
        scannerMode: 'MSBuild'
        projectKey: '2011-nov02-net_project2-fakebook'
        extraProperties: |
          sonar.exclusions=**/lib/**
          sonar.cs.opencover.reportsPaths = $(Agent.TempDirectory)/**/coverage.opencover.xml

    - task: UseDotNet@2
      displayName: 'Use .NET 5 SDK'
      inputs:
        packageType: 'sdk'
        version: '5.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet
        workingDirectory: 'backend/Fakebook/Fakebook.RestApi'

    - script: dotnet build --configuration $(buildConfiguration)
      displayName: dotnet build
      workingDirectory: 'backend/Fakebook/Fakebook.RestApi'

    - task: SonarCloudAnalyze@1
      displayName: sonar run analysis

    - task: SonarCloudPublish@1
      displayName: sonar analysis publish
      inputs:
        pollingTimeoutSec: '300'

    - task: DotNetCoreCLI@2
      displayName: dotnet test
      inputs:
        command: 'test'
        arguments: '--configuration $(BuildConfiguration) --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover'
        publishTestResults: true
        workingDirectory: 'backend/Fakebook/Fakebook.RestApi'

    - script: dotnet publish --configuration $(buildConfiguration) --output publish
      displayName: dotnet publish
      workingDirectory: 'backend/Fakebook/Fakebook.RestApi'
      
    - task: AzureRmWebAppDeployment@4
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure subscription 1(81bd61fe-b8b6-4706-814b-556dc3ff0cc5)'
        appType: 'webAppLinux'
        WebAppName: '2011-project2-fakebook'
        packageForLinux: 'backend/Fakebook/Fakebook.RestApi/publish'
